thirdauth/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'fbauth.views.home', name='home'),
   url(r'^admin/', include(admin.site.urls)),
   url(r'^login/$', 'fbauth.views.login', name='login'),
   url(r'^logout/$', 'fbauth.views.logout', name='logout'),
   url(r'^complete/linkedin-oauth2/$', 'fbauth.views.linkedin_response', name='linkedin'),
   url('', include('django.contrib.auth.urls', namespace='auth')),
   url('', include('social.apps.django_app.urls', namespace='social')),
   # url(r'^linkedin-data/', 'fbauth.views.linkedin_setup')
)

fbauth/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

fbauth/views.py
from django.shortcuts import render, redirect
from linkedin import linkedin
import requests
from django.contrib.auth import logout as auth_logout
import urllib2
import json
from django.shortcuts import render_to_response
from django.template.context import RequestContext


def login(request):
	return render(request, 'login.html')

def logout(request):
    auth_logout(request)
    return redirect('/')

def home(request):
	return render(request, 'home.html')

def linkedin_response(request):
	API_KEY = "75i4121vcmndhp"
	API_SECRET = "Zi6dEWMS9GijIyuS"
	RETURN_URL = "http://9efbc57c.ngrok.io/complete/linkedin-oauth2/"
	code = request.GET.get('code')
	authentication = linkedin.LinkedInAuthentication(API_KEY, API_SECRET, RETURN_URL)
	authentication.authorization_code = code
	token = authentication.get_access_token()
	application = linkedin.LinkedInApplication(token=token)
	print 'profile--------------', application.get_profile(selectors=['id', 'first-name', 'last-name', 'location', 'headline','distance', 'num-connections', 'skills', 'educations','public-profile-url'])
	return render(request, 'login.html')

fbauth/templates/home.html
<html>
</html>

fbauth/templates/login.html
<div>
 <h1>Third-party authentication demo</h1>

 <p>
   <ul>
   {% if user and not user.is_anonymous %}
     <li>
       <a>Hello {{ user.get_full_name|default:user.username }}!</a>
     </li>
     <li>
       <a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a>
     </li>
   {% else %}
     <li>
       <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>
     </li>
     <li>
     	  <a href="{% url 'social:begin' backend='linkedin-oauth2' %}?next={{ request.path }}">Login with Linkedin</a>
     </li>
   {% endif %}
   </ul>
 </p>
 </div>